### ISSUE TITLE
Can't get it to work ...

### ISSUE THREAD

**Issue by Maertuerer** [stefanw/seriesly#6]
Hello everyone,

I hope I might still get some help in here =)
I am trying to set up my own server, but I am getting some errors.
Followed all the steps and now when I start the server I get the following error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\cor
e\handlers\base.py", line 91, in get_response
    request.path_info)
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\cor
e\urlresolvers.py", line 217, in resolve
    sub_match = pattern.resolve(new_path)
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\cor
e\urlresolvers.py", line 123, in resolve
    return self.callback, args, kwargs
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\cor
e\urlresolvers.py", line 129, in _get_callback
    self._callback = get_callable(self._callback_str)
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\uti
ls\functional.py", line 124, in wrapper
    result = func(*args)
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\cor
e\urlresolvers.py", line 56, in get_callable
    lookup_view = getattr(import_module(mod_name), func_name)
  File "C:\Program Files (x86)\Google\google_appengine\lib\django-1.2\django\uti
ls\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\subscription\views.py
", line 16, in <module>
    from series.models import Show, Episode
  File "C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\series\models.py", li
ne 5, in <module>
    from pytz import utc
  File "C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\pytz\__init__.py", li
ne 1021, in <module>
    tz for tz in all_timezones if resource_exists(tz)]
  File "C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\pytz\__init__.py", li
ne 77, in resource_exists
    open_resource(name)
  File "C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\pytz\__init__.py", li
ne 71, in open_resource
    return StringIO(zoneinfo.read(os.path.join('zoneinfo', *name_parts)))
  File "C:\Python27\lib\zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "C:\Python27\lib\zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "C:\Python27\lib\zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'zoneinfo\\\\Africa\\\\Abidjan' in the archive
"
C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\pytz\__init__.py:54: RuntimeW
arning: Parent module 'pytz' not found while handling absolute import
  import zipfile
C:\Users\Dustin\Desktop\Seriesly\seriesly\seriesly\pytz\__init__.py:55: RuntimeW
arning: Parent module 'pytz' not found while handling absolute import
  from cStringIO import StringIO

Maybe someone of youo can help. I already tried installing pytz but that didn't help.

Thanks in advance!

Regards,
Dustin

**Comment by stefanw** [comment]
Seriesly will remove GAE dependency in #8. Closing this.
